###############################################################
# c-callstack implementation by Kangmo Kim at Nanolat Software.
###############################################################

all: backtrace.c
	gcc -g -O0 -rdynamic backtrace.c -o backtrace 

clean:
	rm -f backtrace 
