###############################################################
# c-callstack implementation by Kangmo Kim at Nanolat Software.
###############################################################

all: link.c
	gcc -g -O0 -rdynamic link.c -o link 

clean:
	rm -f link 
