###############################################################
# c-callstack implementation by Kangmo Kim at Nanolat Software.
###############################################################

all: sighandler.c
	gcc -g -O0 -rdynamic sighandler.c -o sighandler 

clean:
	rm -f sighandler 
